// form_react/src/components/Navigation.js
import React from 'react';

const Navigation = ({ currentView, onViewChange }) => {
  return (
    <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
      <div className="container">
        <a className="navbar-brand" href="#" onClick={() => onViewChange('create')}>
          User Management
        </a>
        
        <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
          <span className="navbar-toggler-icon"></span>
        </button>
        
        <div className="collapse navbar-collapse" id="navbarNav">
          <ul className="navbar-nav me-auto">
            <li className="nav-item">
              <a 
                className={`nav-link ${currentView === 'create' ? 'active' : ''}`}
                href="#" 
                onClick={() => onViewChange('create')}
              >
                Create User
              </a>
            </li>
            <li className="nav-item">
              <a 
                className={`nav-link ${currentView === 'list' ? 'active' : ''}`}
                href="#" 
                onClick={() => onViewChange('list')}
              >
                Users List
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  );
};

export default Navigation;

// form_vue/src/components/Navigation.vue
<template>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="#" @click="setCurrentView('create')">
        User Management
      </a>
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a 
              class="nav-link" 
              :class="{ active: currentView === 'create' }"
              href="#" 
              @click="setCurrentView('create')"
            >
              Create User
            </a>
          </li>
          <li class="nav-item">
            <a 
              class="nav-link" 
              :class="{ active: currentView === 'list' }"
              href="#" 
              @click="setCurrentView('list')"
            >
              Users List
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'Navigation',
  props: {
    currentView: {
      type: String,
      required: true
    }
  },
  methods: {
    setCurrentView(view) {
      this.$emit('view-changed', view);
    }
  }
}
</script>
