// form_vue/src/components/App.vue
<template>
  <div>
    <Navigation 
      :currentView="currentView" 
      @view-changed="handleViewChange"
    />
    
    <main>
      <CreateUser v-if="currentView === 'create'" />
      <UsersList 
        v-if="currentView === 'list'" 
        ref="usersList"
        @edit-user="handleEditUser"
        @user-deleted="handleUserDeleted"
      />
    </main>

    <!-- Edit User Modal -->
    <div v-if="showEditModal" class="modal fade show d-block" style="background-color: rgba(0,0,0,0.5)">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Edit User</h5>
            <button type="button" class="btn-close" @click="showEditModal = false"></button>
          </div>
          <div class="modal-body">
            <EditUserInline 
              :user="userToEdit" 
              @user-updated="handleUserUpdated"
              @cancel="showEditModal = false"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Navigation from './Navigation.vue'
import CreateUser from './CreateUser.vue'
import UsersList from './UsersList.vue'
import EditUserInline from './EditUserInline.vue'

export default {
  name: 'App',
  components: {
    Navigation,
    CreateUser,
    UsersList,
    EditUserInline
  },
  data() {
    return {
      currentView: 'create',
      userToEdit: null,
      showEditModal: false
    }
  },
  methods: {
    handleViewChange(view) {
      this.currentView = view;
      this.showEditModal = false;
      this.userToEdit = null;
    },
    
    handleEditUser(user) {
      this.userToEdit = user;
      this.showEditModal = true;
    },
    
    handleUserUpdated() {
      this.showEditModal = false;
      this.userToEdit = null;
      if (this.$refs.usersList) {
        this.$refs.usersList.loadUsers();
      }
    },
    
    handleUserDeleted() {
      if (this.$refs.usersList) {
        this.$refs.usersList.loadUsers();
      }
    }
  }
}
</script>

// form_react/src/App.js
import React, { useState } from 'react';
import './App.css';
import Navigation from './components/Navigation';
import CreateUser from './components/CreateUser';
import UsersList from './components/UsersList';
import EditUserModal from './components/EditUserModal';

function App() {
  const [currentView, setCurrentView] = useState('create');
  const [userToEdit, setUserToEdit] = useState(null);
  const [showEditModal, setShowEditModal] = useState(false);

  const handleViewChange = (view) => {
    setCurrentView(view);
    setShowEditModal(false);
    setUserToEdit(null);
  };

  const handleEditUser = (user) => {
    setUserToEdit(user);
    setShowEditModal(true);
  };

  const handleUserUpdated = () => {
    setShowEditModal(false);
    setUserToEdit(null);
    if (window.usersListRef) {
      window.usersListRef.loadUsers();
    }
  };

  const handleUserDeleted = () => {
    console.log('User deleted, refreshing list if needed');
  };

  return (
    <div className="App">
      <Navigation currentView={currentView} onViewChange={handleViewChange} />
      
      <main>
        {currentView === 'create' && <CreateUser />}
        {currentView === 'list' && (
          <UsersList 
            onEditUser={handleEditUser}
            onUserDeleted={handleUserDeleted}
          />
        )}
      </main>

      {showEditModal && (
        <div className="modal fade show d-block" style={{backgroundColor: 'rgba(0,0,0,0.5)'}}>
          <div className="modal-dialog modal-lg">
            <div className="modal-content">
              <div className="modal-header">
                <h5 className="modal-title">Edit User</h5>
                <button 
                  type="button" 
                  className="btn-close" 
                  onClick={() => setShowEditModal(false)}
                ></button>
              </div>
              <div className="modal-body">
                <EditUserModal 
                  user={userToEdit} 
                  onUserUpdated={handleUserUpdated}
                  onCancel={() => setShowEditModal(false)}
                />
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;
